version: '3.7'

services:
  backend:
    build: ~/Desktop/jars/crm/
    image: crm_backend
    container_name: crm_backend
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=bitlab
      - SPRING_DATASOURCE_PASSWORD=bitlab
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8002:8000

  db:
    image: postgres
    container_name: pg-server
    environment:
        - POSTGRES_USER=bitlab
        - POSTGRES_PASSWORD=bitlab
    ports:
        - 2345:5432

