version: '3.7'

services:
  backend:
    build: .
    image: crm
    container_name: crm-backend
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=bitlab
      - SPRING_DATASOURCE_PASSWORD=bitlab
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    ports:
      - 8001:8001

  db:
    image: postgres
    container_name: pg-server
    environment:
        - POSTGRES_USER=bitlab
        - POSTGRES_PASSWORD=bitlab
    ports:
        - 2345:5432

