create table courses
(
    id          bigint generated by default as identity
        primary key,
    description varchar(255),
    name        varchar(255),
    price       integer
);

create table departments
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255)
);

create table operators
(
    id            bigint generated by default as identity
        primary key,
    name          varchar(255),
    surname       varchar(255),
    department_id bigint
        constraint fknxxyma9rnj801fodhoxj496t2
            references departments
);

create table requests
(
    id        bigint generated by default as identity
        primary key,
    comment   varchar(255),
    handled   boolean,
    phone     varchar(255),
    user_name varchar(255),
    course_id bigint
        constraint fki3kqmlt8l5dc7ctj72t9rn5j4
            references courses
);

create table requests_operator_list
(
    application_request_id bigint not null
        constraint fkmk6nyl6ca5kd1he05lhc7ckjk
            references requests,
    operator_list_id       bigint not null
        constraint fklwyyj436s617kqko1wpdx86v
            references operators
);

create table roles
(
    id   bigint generated by default as identity
        primary key,
    role varchar(255)
);

create table users
(
    id        bigint generated by default as identity
        primary key,
    email     varchar(255),
    full_name varchar(255),
    password  varchar(255)
);

create table users_roles_list
(
    users_id      bigint not null
        constraint fkosmvcvfk27aottdokt5jbuyio
            references users,
    roles_list_id bigint not null
        constraint fk9brgusj2n7ekp6b73u9033k1a
            references roles
);